import 'package:flutter/material.dart';
import 'package:pokemon_vgc/app/service/user_service.dart';

class LoginPageController {
  Future<void> login(
      String username, String password, BuildContext context) async {
    UserService userService = UserService();

  print(username);

    var user = await userService.getUserByName(username);

    if(user?.name == username && user?.password == password){
      //jsonSave.saveJsonToLocalStorage((user?.id).toString(), 'logged_user');
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Sucesso')),
      );
      //Navigator.of(context).pushReplacementNamed('/home');
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Usuário ou senha incorretos')),
      );
    }
  }

  void register(BuildContext context) {
    Navigator.of(context).pushReplacementNamed('/register');
  }
/*
  UserModel createUser() {
    return UserModel(
      id: 0, // O ID será ajustado automaticamente pela função
      name: 'Kannon',
      email: 'kannon@gmail.com',
      password: '123',
      teams: [
        PokemonTeamModel(
          1,
          'Violet',
          PokemonModel(
            name: 'Ceruledge',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Flash Fire',
            hp: 75,
            atk: 125,
            def: 80,
            spa: 60,
            spd: 100,
            spe: 85,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/937.png',
            move1: 'Bitter Blade',
            move2: 'Shadow Sneak',
            move3: 'Close Combat',
            move4: 'Swords Dance',
          ),
          PokemonModel(
            name: 'Meowscarada',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Overgrow',
            hp: 76,
            atk: 110,
            def: 70,
            spa: 81,
            spd: 70,
            spe: 123,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/908.png',
            move1: 'Flower Trick',
            move2: 'Knock Off',
            move3: 'Play Rough',
            move4: 'U-turn',
          ),
          PokemonModel(
            name: 'Lycanroc-dusk',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Tough Claws',
            hp: 75,
            atk: 117,
            def: 65,
            spa: 55,
            spd: 65,
            spe: 110,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10152.png',
            move1: 'Stone Edge',
            move2: 'Accelerock',
            move3: 'Swords Dance',
            move4: 'Close Combat',
          ),
          PokemonModel(
            name: 'Lucario',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Inner Focus',
            hp: 70,
            atk: 110,
            def: 70,
            spa: 115,
            spd: 70,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png',
            move1: 'Close Combat',
            move2: 'Meteor Mash',
            move3: 'Extreme Speed',
            move4: 'Swords Dance',
          ),
          PokemonModel(
            name: 'Sylveon',
            lvl: 50,
            nature: 'Modest',
            ability: 'Pixilate',
            hp: 95,
            atk: 65,
            def: 65,
            spa: 110,
            spd: 130,
            spe: 60,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png',
            move1: 'Hyper Voice',
            move2: 'Mystical Fire',
            move3: 'Protect',
            move4: 'Calm Mind',
          ),
          PokemonModel(
            name: 'Haxorus',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Mold Breaker',
            hp: 76,
            atk: 147,
            def: 90,
            spa: 60,
            spd: 70,
            spe: 97,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/612.png',
            move1: 'Dragon Claw',
            move2: 'Earthquake',
            move3: 'Iron Tail',
            move4: 'Swords Dance',
          ),
        ),
        PokemonTeamModel(
          2, // ID do time
          'Kalos',
          PokemonModel(
            name: 'Greninja',
            lvl: 50,
            nature: 'Timid',
            ability: 'Protean',
            hp: 72,
            atk: 95,
            def: 67,
            spa: 103,
            spd: 71,
            spe: 122,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/658.png',
            move1: 'Hydro Pump',
            move2: 'Dark Pulse',
            move3: 'Ice Beam',
            move4: 'U-turn',
          ),
          PokemonModel(
            name: 'Haxorus',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Mold Breaker',
            hp: 76,
            atk: 147,
            def: 90,
            spa: 60,
            spd: 70,
            spe: 97,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/612.png',
            move1: 'Outrage',
            move2: 'Earthquake',
            move3: 'Poison Jab',
            move4: 'Dragon Dance',
          ),
          PokemonModel(
            name: 'Lucario',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Steadfast',
            hp: 70,
            atk: 110,
            def: 70,
            spa: 115,
            spd: 70,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png',
            move1: 'Close Combat',
            move2: 'Extreme Speed',
            move3: 'Bullet Punch',
            move4: 'Swords Dance',
          ),
          PokemonModel(
            name: 'Charizard',
            lvl: 50,
            nature: 'Modest',
            ability: 'Blaze',
            hp: 78,
            atk: 84,
            def: 78,
            spa: 109,
            spd: 85,
            spe: 100,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
            move1: 'Flamethrower',
            move2: 'Air Slash',
            move3: 'Dragon Pulse',
            move4: 'Solar Beam',
          ),
          PokemonModel(
            name: 'Aurorus',
            lvl: 50,
            nature: 'Modest',
            ability: 'Refrigerate',
            hp: 123,
            atk: 77,
            def: 72,
            spa: 99,
            spd: 92,
            spe: 58,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/699.png',
            move1: 'Freeze-Dry',
            move2: 'Hyper Voice',
            move3: 'Ancient Power',
            move4: 'Thunderbolt',
          ),
          PokemonModel(
            name: 'Gardevoir',
            lvl: 50,
            nature: 'Timid',
            ability: 'Synchronize',
            hp: 68,
            atk: 65,
            def: 65,
            spa: 125,
            spd: 115,
            spe: 80,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png',
            move1: 'Psychic',
            move2: 'Moonblast',
            move3: 'Shadow Ball',
            move4: 'Calm Mind',
          ),
        ),
        PokemonTeamModel(
          3,
          'Alola',
          PokemonModel(
            name: 'Decidueye',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Overgrow',
            hp: 78,
            atk: 107,
            def: 75,
            spa: 100,
            spd: 100,
            spe: 70,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/724.png',
            move1: 'Spirit Shackle',
            move2: 'Leaf Blade',
            move3: 'Sucker Punch',
            move4: 'Brave Bird',
          ),
          PokemonModel(
            name: 'Lycanroc-midday',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Sand Rush',
            hp: 75,
            atk: 115,
            def: 65,
            spa: 55,
            spd: 65,
            spe: 112,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/745.png',
            move1: 'Stone Edge',
            move2: 'Accelerock',
            move3: 'Swords Dance',
            move4: 'Close Combat',
          ),
          PokemonModel(
            name: 'Golisopod',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Emergency Exit',
            hp: 75,
            atk: 125,
            def: 140,
            spa: 60,
            spd: 90,
            spe: 40,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/768.png',
            move1: 'First Impression',
            move2: 'Leech Life',
            move3: 'Liquidation',
            move4: 'Sucker Punch',
          ),
          PokemonModel(
            name: 'Zoroark',
            lvl: 50,
            nature: 'Timid',
            ability: 'Illusion',
            hp: 60,
            atk: 105,
            def: 60,
            spa: 120,
            spd: 60,
            spe: 105,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/571.png',
            move1: 'Night Daze',
            move2: 'Focus Blast',
            move3: 'Flamethrower',
            move4: 'Nasty Plot',
          ),
          PokemonModel(
            name: 'Vikavolt',
            lvl: 50,
            nature: 'Modest',
            ability: 'Levitate',
            hp: 77,
            atk: 70,
            def: 90,
            spa: 145,
            spd: 75,
            spe: 43,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/738.png',
            move1: 'Thunderbolt',
            move2: 'Bug Buzz',
            move3: 'Energy Ball',
            move4: 'Volt Switch',
          ),
          PokemonModel(
            name: 'Espeon',
            lvl: 50,
            nature: 'Timid',
            ability: 'Synchronize',
            hp: 65,
            atk: 65,
            def: 60,
            spa: 130,
            spd: 95,
            spe: 110,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png',
            move1: 'Psychic',
            move2: 'Shadow Ball',
            move3: 'Dazzling Gleam',
            move4: 'Calm Mind',
          ),
        ),
      ],
    );
  }

  UserModel createUser2() {
    return UserModel(
      id: 0, // O ID será ajustado automaticamente pela função
      name: 'Seraph',
      email: 'seraph@gmail.com',
      password: '123',
      teams: [
        PokemonTeamModel(
          1,
          'Eevee',
          PokemonModel(
            name: 'Umbreon',
            lvl: 50,
            nature: 'Calm',
            ability: 'Synchronize',
            hp: 95,
            atk: 65,
            def: 110,
            spa: 60,
            spd: 130,
            spe: 65,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/197.png',
            move1: 'Foul Play',
            move2: 'Toxic',
            move3: 'Wish',
            move4: 'Protect',
          ),
          PokemonModel(
            name: 'Sylveon',
            lvl: 50,
            nature: 'Modest',
            ability: 'Pixilate',
            hp: 95,
            atk: 65,
            def: 65,
            spa: 110,
            spd: 130,
            spe: 60,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png',
            move1: 'Hyper Voice',
            move2: 'Moonblast',
            move3: 'Psyshock',
            move4: 'Calm Mind',
          ),
          PokemonModel(
            name: 'Jolteon',
            lvl: 50,
            nature: 'Timid',
            ability: 'Volt Absorb',
            hp: 65,
            atk: 65,
            def: 60,
            spa: 110,
            spd: 95,
            spe: 130,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
            move1: 'Thunderbolt',
            move2: 'Shadow Ball',
            move3: 'Volt Switch',
            move4: 'Hidden Power Ice',
          ),
          PokemonModel(
            name: 'Glaceon',
            lvl: 50,
            nature: 'Modest',
            ability: 'Snow Cloak',
            hp: 65,
            atk: 60,
            def: 110,
            spa: 130,
            spd: 95,
            spe: 65,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/471.png',
            move1: 'Ice Beam',
            move2: 'Shadow Ball',
            move3: 'Blizzard',
            move4: 'Protect',
          ),
          PokemonModel(
            name: 'Leafeon',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Chlorophyll',
            hp: 65,
            atk: 110,
            def: 130,
            spa: 60,
            spd: 65,
            spe: 95,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/470.png',
            move1: 'Leaf Blade',
            move2: 'Knock Off',
            move3: 'Swords Dance',
            move4: 'Protect',
          ),
          PokemonModel(
            name: 'Espeon',
            lvl: 50,
            nature: 'Timid',
            ability: 'Synchronize',
            hp: 65,
            atk: 65,
            def: 60,
            spa: 130,
            spd: 95,
            spe: 110,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png',
            move1: 'Psychic',
            move2: 'Shadow Ball',
            move3: 'Dazzling Gleam',
            move4: 'Calm Mind',
          ),
        )
      ],
    );
  }

  UserModel createUser3() {
    return UserModel(
      id: 0, // O ID será ajustado automaticamente pela função
      name: 'Ash Ketchum',
      email: 'ash.ketchum@pokemon.com',
      password: 'pikachu',
      teams: [
        // Time Final de Kanto
        PokemonTeamModel(
          1,
          'Kanto',
          PokemonModel(
            name: 'Pikachu',
            lvl: 50,
            nature: 'Hardy',
            ability: 'Static',
            hp: 35,
            atk: 55,
            def: 40,
            spa: 50,
            spd: 50,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
            move1: 'Thunderbolt',
            move2: 'Iron Tail',
            move3: 'Quick Attack',
            move4: 'Electro Ball',
          ),
          PokemonModel(
            name: 'Charizard',
            lvl: 50,
            nature: 'Modest',
            ability: 'Blaze',
            hp: 78,
            atk: 84,
            def: 78,
            spa: 109,
            spd: 85,
            spe: 100,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
            move1: 'Flamethrower',
            move2: 'Dragon Claw',
            move3: 'Air Slash',
            move4: 'Slash',
          ),
          PokemonModel(
            name: 'Bulbasaur',
            lvl: 50,
            nature: 'Calm',
            ability: 'Overgrow',
            hp: 45,
            atk: 49,
            def: 49,
            spa: 65,
            spd: 65,
            spe: 45,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
            move1: 'Razor Leaf',
            move2: 'Solar Beam',
            move3: 'Sleep Powder',
            move4: 'Leech Seed',
          ),
          PokemonModel(
            name: 'Squirtle',
            lvl: 50,
            nature: 'Bold',
            ability: 'Torrent',
            hp: 44,
            atk: 48,
            def: 65,
            spa: 50,
            spd: 64,
            spe: 43,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
            move1: 'Hydro Pump',
            move2: 'Skull Bash',
            move3: 'Ice Beam',
            move4: 'Rapid Spin',
          ),
          PokemonModel(
            name: 'Snorlax',
            lvl: 50,
            nature: 'Relaxed',
            ability: 'Immunity',
            hp: 160,
            atk: 110,
            def: 65,
            spa: 65,
            spd: 110,
            spe: 30,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
            move1: 'Body Slam',
            move2: 'Hyper Beam',
            move3: 'Rest',
            move4: 'Ice Punch',
          ),
          PokemonModel(
            name: 'Pidgeot',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Keen Eye',
            hp: 83,
            atk: 80,
            def: 75,
            spa: 70,
            spd: 70,
            spe: 101,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
            move1: 'Wing Attack',
            move2: 'Quick Attack',
            move3: 'Gust',
            move4: 'Feather Dance',
          ),
        ),

        // Time Final de Kalos
        PokemonTeamModel(
          2,
          'Kalos',
          PokemonModel(
            name: 'Pikachu',
            lvl: 50,
            nature: 'Hardy',
            ability: 'Static',
            hp: 35,
            atk: 55,
            def: 40,
            spa: 50,
            spd: 50,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
            move1: 'Thunderbolt',
            move2: 'Iron Tail',
            move3: 'Quick Attack',
            move4: 'Electro Ball',
          ),
          PokemonModel(
            name: 'Greninja',
            lvl: 50,
            nature: 'Timid',
            ability: 'Battle Bond',
            hp: 72,
            atk: 95,
            def: 67,
            spa: 103,
            spd: 71,
            spe: 122,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/658.png',
            move1: 'Water Shuriken',
            move2: 'Double Team',
            move3: 'Cut',
            move4: 'Aerial Ace',
          ),
          PokemonModel(
            name: 'Talonflame',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Gale Wings',
            hp: 78,
            atk: 81,
            def: 71,
            spa: 74,
            spd: 69,
            spe: 126,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/663.png',
            move1: 'Brave Bird',
            move2: 'Flare Blitz',
            move3: 'Roost',
            move4: 'Swords Dance',
          ),
          PokemonModel(
            name: 'Hawlucha',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Unburden',
            hp: 78,
            atk: 92,
            def: 75,
            spa: 74,
            spd: 63,
            spe: 118,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/701.png',
            move1: 'Flying Press',
            move2: 'High Jump Kick',
            move3: 'Swords Dance',
            move4: 'Stone Edge',
          ),
          PokemonModel(
            name: 'Goodra',
            lvl: 50,
            nature: 'Modest',
            ability: 'Sap Sipper',
            hp: 90,
            atk: 100,
            def: 70,
            spa: 110,
            spd: 150,
            spe: 80,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/706.png',
            move1: 'Dragon Pulse',
            move2: 'Muddy Water',
            move3: 'Ice Beam',
            move4: 'Thunderbolt',
          ),
          PokemonModel(
            name: 'Noivern',
            lvl: 50,
            nature: 'Timid',
            ability: 'Infiltrator',
            hp: 85,
            atk: 70,
            def: 80,
            spa: 97,
            spd: 80,
            spe: 123,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/715.png',
            move1: 'Boomburst',
            move2: 'Air Slash',
            move3: 'Dragon Pulse',
            move4: 'Flamethrower',
          ),
        ),

        // Time Final de Alola
        PokemonTeamModel(
          3,
          'Alola',
          PokemonModel(
            name: 'Pikachu',
            lvl: 50,
            nature: 'Hardy',
            ability: 'Static',
            hp: 35,
            atk: 55,
            def: 40,
            spa: 50,
            spd: 50,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
            move1: 'Thunderbolt',
            move2: 'Iron Tail',
            move3: 'Quick Attack',
            move4: 'Electro Ball',
          ),
          PokemonModel(
            name: 'Incineroar',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Blaze',
            hp: 95,
            atk: 115,
            def: 90,
            spa: 80,
            spd: 90,
            spe: 60,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/727.png',
            move1: 'Darkest Lariat',
            move2: 'Flare Blitz',
            move3: 'Cross Chop',
            move4: 'Throat Chop',
          ),
          PokemonModel(
            name: 'Lycanroc',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Keen Eye',
            hp: 75,
            atk: 115,
            def: 65,
            spa: 55,
            spd: 65,
            spe: 112,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/745.png',
            move1: 'Stone Edge',
            move2: 'Accelerock',
            move3: 'Crunch',
            move4: 'Swords Dance',
          ),
          PokemonModel(
            name: 'Melmetal',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Iron Fist',
            hp: 135,
            atk: 143,
            def: 143,
            spa: 80,
            spd: 65,
            spe: 34,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/809.png',
            move1: 'Double Iron Bash',
            move2: 'Thunder Punch',
            move3: 'Earthquake',
            move4: 'Ice Punch',
          ),
          PokemonModel(
            name: 'Rowlet',
            lvl: 50,
            nature: 'Brave',
            ability: 'Overgrow',
            hp: 68,
            atk: 55,
            def: 55,
            spa: 50,
            spd: 50,
            spe: 42,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/722.png',
            move1: 'Leaf Blade',
            move2: 'Brave Bird',
            move3: 'Razor Leaf',
            move4: 'Seed Bomb',
          ),
          PokemonModel(
            name: 'Naganadel',
            lvl: 50,
            nature: 'Timid',
            ability: 'Beast Boost',
            hp: 73,
            atk: 73,
            def: 73,
            spa: 127,
            spd: 73,
            spe: 121,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/804.png',
            move1: 'Dragon Pulse',
            move2: 'Sludge Bomb',
            move3: 'Thunderbolt',
            move4: 'Flamethrower',
          ),
        ),

        // Time Final de Galar
        PokemonTeamModel(
          4,
          'Galar',
          PokemonModel(
            name: 'Pikachu',
            lvl: 50,
            nature: 'Hardy',
            ability: 'Static',
            hp: 35,
            atk: 55,
            def: 40,
            spa: 50,
            spd: 50,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
            move1: 'Thunderbolt',
            move2: 'Iron Tail',
            move3: 'Quick Attack',
            move4: 'Electro Ball',
          ),
          PokemonModel(
            name: 'Dragonite',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Inner Focus',
            hp: 91,
            atk: 134,
            def: 95,
            spa: 100,
            spd: 100,
            spe: 80,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
            move1: 'Dragon Claw',
            move2: 'Hurricane',
            move3: 'Extreme Speed',
            move4: 'Thunder Punch',
          ),
          PokemonModel(
            name: 'Dracovish',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Strong Jaw',
            hp: 90,
            atk: 90,
            def: 100,
            spa: 70,
            spd: 80,
            spe: 75,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/882.png',
            move1: 'Fishious Rend',
            move2: 'Crunch',
            move3: 'Outrage',
            move4: 'Ice Fang',
          ),
          PokemonModel(
            name: 'Gengar',
            lvl: 50,
            nature: 'Timid',
            ability: 'Cursed Body',
            hp: 60,
            atk: 65,
            def: 60,
            spa: 130,
            spd: 75,
            spe: 110,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
            move1: 'Shadow Ball',
            move2: 'Sludge Bomb',
            move3: 'Focus Blast',
            move4: 'Thunderbolt',
          ),
          PokemonModel(
            name: 'Lucario',
            lvl: 50,
            nature: 'Jolly',
            ability: 'Inner Focus',
            hp: 70,
            atk: 110,
            def: 70,
            spa: 115,
            spd: 70,
            spe: 90,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png',
            move1: 'Aura Sphere',
            move2: 'Meteor Mash',
            move3: 'Extreme Speed',
            move4: 'Close Combat',
          ),
          PokemonModel(
            name: 'Sirfetch’d',
            lvl: 50,
            nature: 'Adamant',
            ability: 'Steadfast',
            hp: 62,
            atk: 135,
            def: 95,
            spa: 68,
            spd: 82,
            spe: 65,
            image:
                'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/865.png',
            move1: 'Leaf Blade',
            move2: 'Meteor Assault',
            move3: 'Brave Bird',
            move4: 'Knock Off',
          ),
        ),
      ],
    );
  }
  */
}

